main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', showmain, name='showmain'),
    path('show/',show, name="introduce"),
    path('Gangneung/',showgang, name="showgang"),
    path('<int:id>',detail, name='detail'),
    path('new/',new, name="new"),
    path('create/',create, name='create'),
    path('edit/<int:id>',edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),

]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    id = models.AutoField(primary_key = True)
    title = models.CharField(max_length=200)
    writer = models. CharField(max_length=100)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to ="post/",blank=True, null=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]

main/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Post
from django.utils import timezone
# Create your views here.
def showmain(request):
    posts = Post.objects.all()
    return render(request, 'main/mainpage.html',{'posts':posts})


def show(request):
    return render(request, 'main/show.html')

def showgang(request):
    return render(request, 'main/Gangneung.html')

def detail(request,id):
    post = get_object_or_404(Post, pk = id)
    return render(request, 'main/detail.html', {'post':post})

def new(request):
    return render(request, 'main/new.html')

def update(request, id):
    update_post = Post.objects.get(id = id)
    update_post.title = request.POST['title']
    update_post.writer = request.POST['writer']
    update_post.pub_date = timezone.now()
    update_post.body = request.POST['body']
    update_post.image = request.FILES.get('image')
    update_post.save()
    return redirect('main:detail',update_post.id)

def create(request):
    new_post = Post()
    new_post.title = request.POST['title']
    new_post.writer = request.POST['writer']
    new_post.pub_date = timezone.now()
    new_post.body = request.POST['body']
    new_post.image = request.FILES.get('image')
    new_post.save()
    return redirect('main:detail',new_post.id)

def edit(request, id):
    edit_post = Post.objects.get(id = id)
    return render(request, 'main/edit.html', {'post' : edit_post})

def delete(request, id):
    delete_post = Post.objects.get(id = id)
    delete_post.delete()
    return redirect('main:showmain')

basic/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>yeoshin's SNS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/project.css' %}">

</head>
<body>
    {%include 'shared/_navbar.html'%}
    
    {% block content %}


    {% endblock %}
   
</body>
</html>

basic/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:showmain' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:introduce' %}">자기소개페이지</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

main/templates/main/Gangneung.html
{% extends 'base.html' %}

{% block content %}


<h1>강릉여행페이지</h1>


{% endblock %}

main/templates/main/detail.html
{% extends 'base.html' %}
{%load static %}

{% block content %}

<h1>{{post.title}}</h1>
작성자 : {{post.writer}}
날짜 : {{post.pub_date}}
<hr>
{%if post.image %}
    <p><img src ="{{post.image.url}}" alt="사진"></p>
{% endif %}
<p>{{post.body}}</p>

<a href="{%url 'main:edit' post.id%}">수정하기</a>
<a href="{%url 'main:delete' post.id%}">삭제하기</a>

{% endblock %}

main/templates/main/edit.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<div class="container">
    <h1>글 수정하기</h1>
    <form action="{%url 'main:update' post.id %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목: <input type="text" name="title" value ="{{post.title}}"></p>
        <p>작성자: <input type="text" name="writer" value="{{post.writer}}"></p>
        <p>사진: <input type="file" name="image"></p>
        <p>내용: <textarea type="text" name="body" id="" cols="30" rows="10">{{post.body}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</div>

{% endblock %}

main/templates/main/mainpage.html
{% extends 'base.html' %}

{%load static %}

{% block content %}
    <h1>01__goddess</h1> 
    <div class="trip_box">
        <p>부산여행🚅</p>
        <p>속초여행🚌</p>
        <div class="atag">
            <a href="{% url 'main:showgang' %}">강릉여행🏖</a>
        </div>
        <p>포항여행🌺</p>
        <p>인천여행😊</p>
    </div>

<div class="atag">
    <a href="{% url 'main:introduce' %}">자기소개페이지</a>
</div>

<h3><a href="{%url 'main:new'%}">글쓰기</a></h3>
<h1>글목록</h1>

<div>
    {% for post in posts %}
    <div>
        <h3>{{post.title}}</h3>
        {{post.writer}}<br>
        {{post.summary}}
        <a href="{%url 'main:detail' post.id %}">...자세히</a>
        <br>
    </div>
    {%endfor%}
</div>

{% endblock %}

main/templates/main/new.html
{% extends 'base.html' %}
{%load static %}

{% block content %}

<form action="{%url 'main:create'%}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <p>제목 : <input type='text' name='title'></p>
    <p>작성자 : <input type='text' name='writer'></p>
    <p>사진 : <input type='file' name ="image"></p>
    <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

main/templates/main/show.html
{% extends 'base.html' %}

{% load static%}
{% block content %}

<link rel="stylesheet" href="show.css">
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <img src= "{% static 'images/logo.png'%}" width="30" height="24" class="d-inline-block align-text-top">
            자기소개페이지
          </a>
        </div>
      </nav>

    <main>
    <div class="header">
        <h1>장여신</h1>
        <a>안녕하세요!</a>
    </div>
    
    <div class="content">
        <p>생년월일 : 2001.02.23</p>
        <p>국제통상학과 20학번 / 통계학과 복전중</p>
        <p>MBTI : ESTJ</p>
        <p>쌍문동 거주</p>
        <p>취미 : 큐브맞추기 / 넷플릭스보기</p>
        <a href="https://www.youtube.com/watch?v=H8heXBOqBg4" class="cube"> 큐브맞추는방법</a>
      </div>
    
    </main>
  <style>
    .header{
    text-align : center;
}
.content{
    font-weight: 400px;
    text-align : center;
    margin-right : 10%;
    margin-left : 10%;
    margin-top: 4%;
    margin-bottom : 10%;
    border: 1px solid gray
}

.cube { text-decoration: none;}

p{color: rgb(255, 123, 0);}
  </style>
  



    
    {% endblock %}